openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger - Desafio Backend Aquarela
servers:
  - url: http://localhost:5000
paths:
  /colaborador:
    get:
      summary: Listar Colaboradores
      description: Requisição para listar todos colaboradores.
      operationId: listCol
      tags:
        - Colaboradores
      parameters:
        - name: limit
          in: query
          description: Quantidade de itens a retornar
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Colaboradores encontrados
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Colaborador"
        '500':
          description: Colaboradores nao encontrados (Erro interno servidor)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /colaborador/{matricula}:
    get:
      summary: Info de Colaborador Especifico
      description: Requisição para pesquisar dados de colaborador via matricula.
      operationId: ListColEsp
      tags:
        - Colaborador
      parameters:
        - name: matricula
          in: path
          required: true
          description: Entre com a matricula do colaborador
          schema:
            type: string
      responses:
        '200':
          description: Colaborador encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Colaborador"
        '404':
          description: Colaborador nao encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Guardar Colaborador
      description: Requisição para guardar novo colaborador via matricula.
      operationId: saveCol
      tags:
      - Colaborador
      parameters:
        - name: matricula
          in: path
          required: true
          description: Entre com a matricula do colaborador a ser adicionado
          schema:
            type: string
      requestBody:
        description: Entre com as infos do colaborador a ser adicionado
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Info_Colaborador'                             
      responses:
        '201':
          description: Colaborador adicionado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Colaborador"
        '400':
          description: Colaborador ja existe
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Erro interno tentando salvar.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
      - Colaborador
      summary: Updated Colaborador
      description: Requisição que pode ser usada para atualizar colaborador ou adicionar colaborador via matricula.
      operationId: updateCol
      parameters:
        - name: "matricula"
          in: "path"
          description: Entre com a matricula do colaborador a ser atualizado/adicionado
          required: true
          schema:
            type: "string"
      requestBody:
        description: Entre com as infos do colaborador a ser atualizado/adicionado
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Info_Colaborador'     
      responses:
        '200':
          description: Colaborador atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Colaborador"
        '201':
          description: Colaborador adicionado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Colaborador"
        "500":
          description: Erro interno tentando salvar
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
      - Colaborador
      summary: "Delete Colaborador"
      description: Requisição para deletar colaborador via matricula.
      operationId: deleteCol
      parameters:
        - name: matricula
          in: "path"
          description: Entre com a matricula do colaborador a ser deletado
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: Colaborador deletado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Colaborador"
        "500":
          description: Erro interno servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Colaborador nao encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Colaborador:
        allOf:
        - $ref: '#/components/schemas/Info_Colaborador'
        type: object
        required:
          - matricula
        properties:
          matricula:
            type: string
    Info_Colaborador:
      type: object
      properties:        
        nome:
          type: string
        sobrenome:
          type: string
        cargo:
          type: string
        codigo_cargo:
          type: string
        lider:
          type: string
        matricula_lider:
          type: string
        salario:
          type: string
        senha:
          type: string
        status_colaborador:
          type: string
    Error:
      type: object
      required:
        - mensage
        - codigo
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32